const constants = {
  SORT_USERS: "SORT_USERS",
  ADD_USER: "ADD_USER",
  EDIT_USER: "EDIT_USER",
  REMOVE_USER: "REMOVE_USER",
  SORT_PRODUCTS: "SORT_PRODUCTS",
  ADD_PRODUCT: "ADD_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT"
}

export default constants;
